### ISSUE TITLE
Air Spin

### ISSUE THREAD

**Issue by Yairb27** [MoonfaceDev/Heroes-of-the-Shrine#33]
Angel Should learn this. (סיבוב באוויר)
instructions are in The Game Plan

**Comment by MoonfaceDev** [comment]
Done, use negative knockback direction

**Comment by MoonfaceDev** [comment]
Reopening and assigning you, you should add it to the game (component + button in player controller + animation + animator state)

**Comment by Yairb27** [comment]
you forgot hitbox like I have forgotten to use capital letter in the start of this sentence
